runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  QDRANT_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.V_Ac_d-IoMjG2Cl_CcFYqpJaB7E8yfPjmQvjAEFDDNs"
  QDRANT_URL: "https://a5f085b1-bd24-4395-847b-f40a09a64415.us-west-2-0.aws.cloud.qdrant.io"
  GEMINI_API_KEY: "AIzaSyDe8DIz9uSPgDVtXKQ9chzuflcH85ZPZcs"
  
handlers:
  - url: /.*
    script: auto
